# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ 'release/v[0-9]+.[0-9]+' ]
    
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    - name: Deploy
      run: |
        npm i -g @railway/cli
        RAILWAY_TOKEN=f460f5c0-bb58-46bf-84cb-b0069f93f751 railway up
    - name: Send custom JSON data to Slack workflow
      id: slack
      uses: slackapi/slack-github-action@v1.23.0
      with:
        # For posting a rich message using Block Kit
        payload: |
            {
            "blocks": [
              {
                "type": "header",
                "text": {
                  "type": "plain_text",
                  "text": "DipSA 56 CI/CD Submission",
                  "emoji": true
                }
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "*Name:*\nDeng Xiya"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Email:*\ne1112946@u.nus.edu"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Matriculation:*\nA0269563N"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Repository:*\nhttps://github.com/lyfer233/dov-bear"
                  }
                ]
              },
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "https://dov-bear-production-29e3.up.railway.app/"
                },
                "accessory": {
                  "type": "button",
                  "text": {
                    "type": "plain_text",
                    "text": "Go",
                    "emoji": true
                  },
                  "value": "click_me_123",
                  "url": "https://dov-bear-production-29e3.up.railway.app/",
                  "action_id": "button-action"
                }
              }
            ]
            }

      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK

      
          
        
